apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust
spec:
  selector:
    matchLabels:
      app: locust
  template:
    metadata:
      labels:
        app: locust
    spec:
      containers:
      - image: {{.Values.image}}
        imagePullPolicy: "IfNotPresent"
        name: locust
        ports:
        - containerPort: 8089
        resources: {}
        volumeMounts:
        - name: locust-volume
          mountPath: /mnt/locust
      volumes:
        - name: locust-volume
          configMap:
            name: locust-config
            items:
            - key: "locust"
              path: "locustfile.py"


