apiVersion: v1
kind: ConfigMap
metadata:
  name: sfx-config
data:
  agentFile: | 
{{.Values.agent | b64dec  | indent 4}}
  traceUrl: | 
{{.Values.traceUrl | toYaml | indent 4}}
  token: | 
{{.Values.token | toYaml | indent 4}}
  ingestUrl: | 
{{.Values.ingestUrl | toYaml | indent 4}}
  apiUrl: | 
{{.Values.ingestUrl | toYaml | indent 4}}