apiVersion: apps/v1
kind: Deployment
metadata:
  name: sfx-agent
spec:
  selector:
    matchLabels:
      app: sfx-agent
  template:
    metadata:
      labels:
        app: sfx-agent
    spec:
      containers:
      - image: {{.Values.image}}
        imagePullPolicy: "IfNotPresent"
        name: sfx-agent
        ports:
        - containerPort: 9080
        resources: {}
        volumeMounts:
        - name: sfx-volume
          mountPath: /etc/signalfx
      volumes:
        - name: sfx-volume
          configMap:
            name: sfx-config
            items:
            - key: "agentFile"
              path: "agent.yaml"
            - key: "traceUrl"
              path: "traceUrl"
            - key: "token"
              path: "token"
            - key: "ingestUrl"
              path: "ingestUrl"
            - key: "apiUrl"
              path: "apiUrl"
