apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - args: ["splk-py-trace", "python3", "app.py"]
        env:
        - name: DEBUG
          value: "True"
        - name: NAMESPACE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SPLUNK_OTEL_AGENT
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://${SPLUNK_OTEL_AGENT}:4317"
        - name: OTEL_EXPORTER_JAEGER_ENDPOINT
          value: "http://${SPLUNK_OTEL_AGENT}:9080/v1/trace"
        image: daz2.jfrog.io/daz-srelabs/foodtruck-web:1.0.0
        imagePullPolicy: Always
        name: foodtruck
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 5000
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  type: LoadBalancer
  ports:
  - name: web
    port: 5000
    targetPort: 5000
  selector:
    app: web
